/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package com.josescalia.tumblr.app.core;

import javax.swing.*;
import java.awt.*;

/**
 *
 * @author josescalia
 */
public class ApplicationSplash extends JFrame {

    /**
     * Creates new form ApplicationSplash
     */
    public ApplicationSplash() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new JPanel();
        lblImage = new JLabel();
        progressBar = new JProgressBar();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(java.awt.Color.white);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(400, 318));
        setResizable(false);

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setBorder(null);
        jPanel1.setLayout(new java.awt.BorderLayout());

        lblImage.setBackground(java.awt.Color.white);
        jPanel1.add(lblImage, java.awt.BorderLayout.CENTER);

        progressBar.setBorder(null);
        progressBar.setString("Initializing...");
        progressBar.setStringPainted(true);
        jPanel1.add(progressBar, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JPanel jPanel1;
    private JLabel lblImage;
    private JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables


    private void centerMe() {
        pack();
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        java.awt.Dimension dialogSize = getSize();
        setLocation((screenSize.width-dialogSize.width)/2,(screenSize.height-dialogSize.height)/2);
    }

    public void setSplashImage(ImageIcon icon) {
        lblImage.setIcon(icon);
        centerMe();
    }

    public void updateProgress(final int value) {
        SwingUtilities.invokeLater( new Runnable() {
            @Override
            public void run() {
                progressBar.setValue(value);
            }
        });

    }

    public void updateStatus(final String status) {
        SwingUtilities.invokeLater( new Runnable() {
            @Override
            public void run() {
                progressBar.setString(status);
            }
        });
    }


}
